mysql:
  image: mysql:5.6.26
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_USER=pet
   - MYSQL_PASSWORD=clinic
   - MYSQL_DATABASE=petclinic
  ports:
    - "3306:3306"
  volumes:
    - ./src/main/resources/db/mysql:/docker-entrypoint-initdb.d
